CREATE DATABASE eletrodomesticos_saep_db;
USE eletrodomesticos_saep_db;

CREATE TABLE ESTOQUE (
    ESTOQUE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ESTOQUE_QUANTIDADE INTEGER,
    FK_ELETRODOMESTICO_ID INTEGER 
);

CREATE TABLE LOGS (
    LOG_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LOG_DESCRICAO VARCHAR(255),
    LOG_DATA_HORA DATE
);

CREATE TABLE ELETRODOMESTICO (
    ELETRO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ELETRO_CATEGORIA VARCHAR(255),
    ELETRO_FORNECEDOR VARCHAR(255),
    ELETRO_PRIORIDADE_REPOSICAO VARCHAR(255),
    ELETRO_POTENCIA VARCHAR(255),
    ELETRO_CONSUMO_ENERGETICO VARCHAR(255),
    ELETRO_GARANTIA DATE,
    FK_USU_ID INTEGER
);

CREATE TABLE USUARIO (
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(255),
    USU_EMAIL VARCHAR(255) UNIQUE,
    USU_SENHA VARCHAR(255)
);
 
ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_2
    FOREIGN KEY (FK_ELETRODOMESTICO_ID)
    REFERENCES ESTOQUE (ESTOQUE_ID) ON DELETE CASCADE;
 
ALTER TABLE ELETRODOMESTICO ADD CONSTRAINT FK_ELETRODOMESTICO_2
    FOREIGN KEY (FK_USU_ID)
    REFERENCES USUARIO (USU_ID) ON DELETE CASCADE;
    
INSERT INTO USUARIO (USU_EMAIL, USU_SENHA, USU_NOME)
VALUES 				("gabriel@email.com","12345678", "Gabriel"),
					("leo@email.com","874659757", "Leonardo"),
					("luiz@email.com","@123@456", "Luiz");
                    
INSERT INTO ELETRODOMESTICO (ELETRO_CATEGORIA, ELETRO_FORNECEDOR, ELETRO_PRIORIDADE_REPOSICAO, ELETRO_POTENCIA, ELETRO_CONSUMO_ENERGETICO, ELETRO_GARANTIA, FK_USU_ID)
VALUES 	('Geladeira', 'Brastemp', 'Alta', 220, 45.6, '2025-05-08', 1),
		('Micro-ondas', 'Electrolux', 'Média', 110, 32.4, '2026-09-12', 2),
        ('Máquina de Lavar', 'LG', 'Baixa', 220, 60.2, '2025-12-09', 3);
        
INSERT INTO ESTOQUE (ESTOQUE_QUANTIDADE, FK_ELETRODOMESTICO_ID)
VALUES 				(5,1),
					(10,2),
                    (20,3);